import type { Metadata } from "next";
import "./globals.css";
import { SparklesCore } from "@/components/ui/sparkles";
import SnowfallCanvas from "@/components/SnowfallCanvas";
import CursorGlow from "@/components/CursorGlow";
import { GridBackground } from "@/components/ui/GridBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full">
      <body className={`antialiased h-full relative flex justify-center`}>
        {children}
        <SnowfallCanvas />
        <CursorGlow />
        <GridBackground />
      </body>
    </html>
  );
}
